version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-github-actions-packages:
        patterns:
          - "*"

  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/docs"
      - "/test"
      - "/test/floattypes"
      - "/test/integration/enzyme"
    schedule:
      interval: "weekly"
    groups:
      all-julia-packages:
        patterns:
          - "*"
