name: MicroBenchmarks

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  # pull_request:
  #   types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia -e 'using Pkg; pkg"""add JSON GitHub DataFrames BenchmarkTools;"""'
      - name: Run benchmarks
        # `if` to temporarily disable the benchmark action
        # if: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BENCHMARK_KEY: ${{ secrets.BENCHMARK_KEY }}
        run: julia ./benchmarks/github-action-runner.jl
