name: Anything else
description: An issue that doesn't fit into any of the other categories
labels: []
projects: ["TuringLang/3"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an issue to Turing.jl!
        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue you encountered.
    validations:
      required: true

  - type: textarea
    id: versioninfo
    attributes:
      label: Julia version info
      description: If relevant, paste the output of `versioninfo()` here
      render: julia

  - type: textarea
    id: manifest
    attributes:
      label: Manifest
      description: If relevant, paste the output of `]st --manifest` here
      render: julia
